- name: Install PXE Components
  hosts: localhost
  become: true
  tasks:

    - name: Install TFTP, HTTP and DHCP
      ansible.builtin.dnf:
        name: tftp-server,dhcp-server,httpd
        state: latest

    - name: Install Boot Files
      ansible.builtin.dnf:
        name: syslinux,shim-x64,grub2-efi-x64
        installroot: /opt/syslinux
        state: present

    - name: Set Up BIOS Boot Dir
      ansible.builtin.file:
        path: "/var/lib/tftpboot/bios/pxelinux.cfg"
        state: directory

    - name: Copy BIOS Boot Files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/lib/tftpboot/bios
      with_items:
        - /opt/syslinux/usr/share/syslinux/pxelinux.0
        - /opt/syslinux/usr/share/syslinux/menu.c32
        - /opt/syslinux/usr/share/syslinux/vesamenu.c32
        - /opt/syslinux/usr/share/syslinux/ldlinux.c32
        - /opt/syslinux/usr/share/syslinux/libcom32.c32
        - /opt/syslinux/usr/share/syslinux/libutil.c32

    - name: Set Up UEFI Boot Dir
      ansible.builtin.file:
        path: "/var/lib/tftpboot/uefi"
        state: directory
       
    - name: Copy UEFI Boot Files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/lib/tftpboot/uefi
      with_items:
        - /opt/syslinux/boot/efi/EFI/fedora/shimx64.efi
        - /opt/syslinux/boot/efi/EFI/fedora/grubx64.efi

    - name: Set Up Kernel Dir
      ansible.builtin.file:
        path: /var/lib/tftpboot/f36
        state: directory

    - name: Get Kernel and Initrd
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /var/lib/tftpboot/f36
      with_items:
        - https://download.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/os/images/pxeboot/vmlinuz
        - https://download.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/os/images/pxeboot/initrd.img

    - name: Write Local Install Repo File
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/f36-inst.local.repo
        content: |
          [f36-inst.local]
          name=Fedora 36 Local Install Repo
          baseurl=https://download.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/os/
          enabled=1
          gpgcheck=0

    - name: Sync Local Install Repo
      ansible.builtin.shell:
        cmd: dnf reposync -a noarch -a x86_64 --delete --download-metadata --download-path /var/www/html/ --repoid f36-inst.local

    - name: Make Image Directory
      ansible.builtin.file:
        path: /var/www/html/f36-inst.local/images/
        state: directory

    - name: Get Install Image
      ansible.builtin.get_url:
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/os/images/install.img
        dest: /var/www/html/f36-inst.local/images/
        
    - name: Get Other Install Files
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /var/www/html/f36-inst.local/
      with_items:
        - https://download.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/os/.treeinfo
        - https://download.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/os/.discinfo

    - name: Write DHCP Config
      ansible.builtin.template:
        src: dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
        backup: yes

    - name: Write BIOS Boot Menu
      ansible.builtin.template:
        src: default
        dest: /var/lib/tftpboot/bios/pxelinux.cfg/default

    - name: Write UEFI Boot Menu
      ansible.builtin.template:
        src: grub.cfg
        dest: /var/lib/tftpboot/uefi/grub.cfg

    - name: Open DHCP, HTTP and TFTP in Firewall
      ansible.builtin.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items:
        - dhcp
        - tftp
        - http

    - name: Enable and Restart DHCP
      ansible.builtin.systemd:
        name: dhcpd
        state: restarted
        enabled: yes

    - name: Enable and Start TFTP and HTTP
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - tftp.socket
        - httpd

  
  