- name: Install PXE Components
  hosts: localhost
  become: true
  tasks:

    - name: Install TFTP, HTTP and DHCP
      ansible.builtin.dnf:
        name: tftp-server,dhcp-server,httpd
        state: latest

    - name: Install Boot Files
      ansible.builtin.dnf:
        name: syslinux,shim-x64,grub2-efi-x64
        installroot: /opt/syslinux
        state: present

    - name: Set Up BIOS Boot Dir
      ansible.builtin.file:
        path: "/var/lib/tftpboot/bios/pxelinux.cfg"
        state: directory

    - name: Copy BIOS Boot Files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/lib/tftpboot/bios
      with_items:
        - /opt/syslinux/usr/share/syslinux/pxelinux.0
        - /opt/syslinux/usr/share/syslinux/menu.c32
        - /opt/syslinux/usr/share/syslinux/vesamenu.c32
        - /opt/syslinux/usr/share/syslinux/ldlinux.c32
        - /opt/syslinux/usr/share/syslinux/libcom32.c32
        - /opt/syslinux/usr/share/syslinux/libutil.c32

    - name: Set Up UEFI Boot Dir
      ansible.builtin.file:
        path: "/var/lib/tftpboot/uefi"
        state: directory
       
    - name: Copy UEFI Boot Files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/lib/tftpboot/uefi
      with_items:
        - /opt/syslinux/boot/efi/EFI/fedora/shimx64.efi
        - /opt/syslinux/boot/efi/EFI/fedora/grubx64.efi

    - name: Set Up Kernel Dir
      ansible.builtin.file:
        path: /var/lib/tftpboot/f36
        state: directory

    - name: Get Kernel and Initrd
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /var/lib/tftpboot/f36
      with_items:
        - https://download.fedoraproject.org/pub/fedora/linux/releases/36/Server/x86_64/os/images/pxeboot/vmlinuz
        - https://download.fedoraproject.org/pub/fedora/linux/releases/36/Server/x86_64/os/images/pxeboot/initrd.img

    - name: Prep for ISO Extraction
      ansible.builtin.file:
        path: /opt/iso/extract
        state: directory

    - name: Get ISO
      ansible.builtin.get_url:
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/36/Server/x86_64/iso/Fedora-Server-dvd-x86_64-36-1.5.iso
        dest: /opt/iso

    - name: Mount ISO
      ansible.builtin.shell:
        cmd: mount /opt/iso/Fedora-Server-dvd-x86_64-36-1.5.iso /opt/iso/extract

    - name: Copy ISO Files to Web Dir
      ansible.builtin.copy:
        src: /opt/iso/extract/
        dest: /var/www/html/f36

    - name: Unmount ISO
      ansible.builtin.shell:
        cmd: umount /opt/iso/extract

    - name: Write DHCP Config
      ansible.builtin.copy:
        dest: /etc/dhcp/dhcpd.conf
        backup: yes
        content: |
          option arch code 93 = unsigned integer 16;
          
           subnet 192.168.1.0 netmask 255.255.255.0 {
            if option arch = 00:07 {
              # x64 UEFI
              filename "uefi/shimx64.efi";
              next-server 192.168.1.250;
            } else {
              # BIOS
              filename "pxelinux.cfg/pxelinux.0";
              next-server 192.168.1.250;
            }
            authoritative;
            default-lease-time 600;
            max-lease-time 7200;
            ddns-update-style none;
            range 192.168.1.1 192.168.1.254;
            
            option domain-name-servers 8.8.8.8;
            option routers 192.168.1.254;
          
          }

    - name: Write BIOS Boot Menu
      ansible.builtin.copy:
        dest: /var/lib/tftpboot/bios/pxelinux.cfg/default
        content: |
          default vesamenu.c32
          prompt 1
          timeout 600

          label local
          menu label Boot from ^local drive
          menu default
          localboot 0xffff
        
          label linux
          menu label ^Install Fedora 36 64-bit
          kernel f36/vmlinuz
          append initrd=f36/initrd.img inst.stage2=https://download.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/os/ ip=dhcp
        
          label server
          menu label ^Install Fedora 36 ( Minimal Image )
          kernel f36/vmlinuz
          append initrd=f36/initrd.img inst.stage2=https://download.fedoraproject.org/pub/fedora/linux/releases/36/Server/x86_64/os/ ip=dhcp ks=https://example.com/fedora/kickstarts/minimal.ks

    - name: Write UEFI Boot Menu
      ansible.builtin.copy:
        dest: /var/lib/tftpboot/uefi/grub.cfg
        content: |
          function load_video {
            insmod efi_gop
            insmod efi_uga
            insmod video_bochs
            insmod video_cirrus
            insmod all_video
          }
          
          load_video
          set gfxpayload=keep
          insmod gzio
        
          menuentry 'Exit this grub' {
            exit
          }
        
          menuentry 'Install Fedora 64-bit'  --class fedora --class gnu-linux --class gnu --class os {
            linuxefi f36/vmlinuz ip=dhcp inst.repo=https://download.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/os/
            initrd f36/initrd.img
          }
        
          menuentry 'Install Fedora 36 Server'  --class fedora --class gnu-linux --class gnu --class os {
            linuxefi f36/vmlinuz inst.repo=https://download.fedoraproject.org/pub/fedora/linux/releases/36/Server/x86_64/os/ ip=dhcp ks=https://git.fedorahosted.org/cgit/spin-kickstarts.git/plain/fedora-install-server.ks?h=f21
            initrd f36/initrd.img
          }

    - name: Open DHCP and TFTP in Firewall
      ansible.builtin.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
      with_items:
        - dhcp
        - tftp
        - http

    - name: Enable and Restart DHCP
      ansible.builtin.systemd:
        name: dhcpd
        state: restarted
        enabled: yes

    - name: Enable and Start TFTP and HTTP
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - tftp.socket
        - httpd

  
  