- name: Install PXE Components
  hosts: localhost
  become: true
  tasks:

   - name: Install TFTP
     ansible.builtin.dnf:
       name: tftp-server
       state: latest

   - name: Install Boot Files
     ansible.builtin.dnf:
       name: syslinux,shim-x64,grub2-efi-x64
       installroot: /opt/syslinux
       state: present

   - name: Set Up BIOS Boot Dir
     ansible.builtin.file:
       path: "/var/lib/tftpboot/pxelinux.cfg"
       state: directory

   - name: Copy BIOS Boot Files
     ansible.builtin.copy:
       src: "{{ item }}"
       dest: /var/lib/tftpboot/pxelinux.cfg
     with_items:
       - /opt/syslinux/usr/share/syslinux/pxelinux.0
       - /opt/syslinux/usr/share/syslinux/menu.c32
       - /opt/syslinux/usr/share/syslinux/vesamenu.c32
       - /opt/syslinux/usr/share/syslinux/ldlinux.c32
       - /opt/syslinux/usr/share/syslinux/libcom32.c32
       - /opt/syslinux/usr/share/syslinux/libutil.c32

   - name: Set Up UEFI Boot Dir
     ansible.builtin.file:
       path: "/var/lib/tftpboot/uefi"
       state: directory
       
   - name: Copy UEFI Boot Files
     ansible.builtin.copy:
       src: "{{ item }}"
       dest: /var/lib/tftpboot/uefi
     with_items:
       - /opt/syslinux/boot/efi/EFI/rocky/shimx64.efi
       - /opt/syslinux/boot/efi/EFI/rocky/grubx64.efi

   - name: Write DHCP Config
     ansible.builtin.copy:
       dest: /etc/dhcp/dhcpd.conf
       content: |
         subnet 192.168.1.0 netmask 255.255.255.0 {
          if option arch = 00:07 {
            # x64 UEFI
            filename "uefi/shimx64.efi";
            next-server 192.168.1.2;
          } else {
            # BIOS
            filename "pxelinux.cfg/pxelinux.0";
            next-server 192.168.1.2;
          }
          authoritative;
          default-lease-time 600;
          max-lease-time 7200;
          ddns-update-style none;
          
          option domain-name-servers 192.168.1.1;
          option routers 192.168.1.1;
          
         }