- name: Post Install for Basic Workstation
  hosts: localhost
  become: true
  tasks:

    - name: Update All (except kernel)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        exclude: kernel-core,kernel-modules

    - name: Install Desktop Tweaks
      ansible.builtin.dnf:
        name:
          - gnome-extensions-app
          - gnome-tweaks
          - gnome-shell-extension-frippery-applications-menu
          - gnome-shell-extension-apps-menu
          - gnome-shell-extension-caffeine
          - gnome-shell-extension-no-overview
          - gnome-shell-extension-window-list
        state: latest
    
    - name: Install Other Repo RPMs
      ansible.builtin.dnf:
        name:
          - https://forensics.cert.org/cert-forensics-tools-release-36.rpm
          - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        state: installed

    - name: Write Manual Repo (vscode)
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc

    - name: Install Tools Packages
      ansible.builtin.dnf:
        name: mono-devel,net-tools,nmap,putty,screen,suricata,tcpdump,tcpreplay,wireshark,yara,yubioath-desktop,google-chrome-stable,code,brim,zeek,Autopsy,Volatility,avml
        state: latest

    - name: Get NetworkMiner Zip
      ansible.builtin.get_url:
        - url: https://www.netresec.com/?download=NetworkMiner
        - dest: /tmp/nm.zip
    
    - name: Extract and chmod NetworkMiner
      ansible.builtin.command:
        cmd: "{{ item }}"
      with_items: 
        - unzip /tmp/nm.zip -d /opt/
        - chmod +x /opt/NetworkMiner*/NetworkMiner.exe
        - chmod -R go+w /opt/NetworkMiner*/AssembledFiles
        - chmod -R go+w /opt/NetworkMiner*/Captures

    - name: Write NetworkMiner Desktop File
      ansible.builtin.copy:
        dest: /usr/share/applications/NetworkMiner.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=Network Miner
          Exec=mono /opt/NetworkMiner.exe --noupdatecheck