- name: Post Install for Basic Workstation
  hosts: localhost
  become: true
  tasks:

    - name: Update All (except kernel)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        exclude: kernel-core,kernel-modules

    - name: Install Desktop Tweaks
      ansible.builtin.dnf:
        name:
          - gnome-extensions-app
          - gnome-tweaks
          - gnome-shell-extension-frippery-applications-menu
          - gnome-shell-extension-apps-menu
          - gnome-shell-extension-caffeine
          - gnome-shell-extension-no-overview
          - gnome-shell-extension-window-list
        state: latest
    
    - name: Install CERT Repo Keys
      ansible.builtin.command:
        cmd: "{{ item }}"
      with_items:
        - rpm --import https://forensics.cert.org/forensics.asc
        - rpm --import https://www.cert.org/forensics/repository/forensics-expires-2022-04-03.asc

    - name: Install Other Repo RPMs
      ansible.builtin.dnf:
        name:
          - https://forensics.cert.org/cert-forensics-tools-release-36.rpm
          - fedora-workstation-repositories
        state: installed

    - name: Write vscode Repo
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/vscode.repo
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=0
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc

    # - name: Write PowerShell Repo
    #   ansible.builtin.copy:
    #     dest: /etc/yum.repos.d/microsoft.repo
    #     content: |
    #       [powershell]
    #       name=PowerShell
    #       baseurl=https://packages.microsoft.com/rhel/8/prod
    #       enabled=0
    #       gpgcheck=1
    #       gpgkey=https://packages.microsoft.com/keys/microsoft.asc

    - name: Get NetworkMiner Zip
      ansible.builtin.get_url:
        url: https://www.netresec.com/?download=NetworkMiner
        dest: /tmp/nm.zip
    
    - name: Extract NetworkMiner
      ansible.builtin.unarchive:
        src: /tmp/nm.zip
        dest: /opt

    - name: chmod NetworkMiner Files
      ansible.builtin.shell:
        cmd: "{{ item }}"
      with_items: 
        - chmod +x /opt/NetworkMiner*/NetworkMiner.exe
        - chmod -R go+w /opt/NetworkMiner*/AssembledFiles
        - chmod -R go+w /opt/NetworkMiner*/Captures
        - mv networkminer.png /opt/NetworkMiner*

    - name: Get NM exe Location
      ansible.builtin.find:
        patterns: "*NetworkMiner.exe"
        paths: "/opt"
        recurse: yes
      register: nmexelocation

    - name: Get NM icon Location
      ansible.builtin.find:
        patterns: "*networkminer.png"
        paths: "/opt"
        recurse: yes
      register: nmiconlocation

    - name: Write NetworkMiner Desktop File
      ansible.builtin.copy:
        dest: /usr/share/applications/NetworkMiner.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=Network Miner
          Exec=mono {{ nmexelocation.files[0].path }} --noupdatecheck
          Icon={{ nmiconlocation.files[0].path }}

    - name: Install Tools Packages
      ansible.builtin.dnf:
        name:
          - mono-devel
          - net-tools
          - nmap
          - putty
          - screen
          - suricata
          - tcpdump
          - tcpreplay
          - wireshark
          - yara
          - yubioath-desktop
          - google-chrome-stable
          - code
          - brim
          - zeek
          - autopsy
          - Volatility
          - avml
          - gcc
          - opensc
          - openssl
          - expect
          # - powershell
        state: latest
        enablerepo: google-chrome,code #,powershell

    - name: Download Horizon Client
      ansible.builtin.get_url:
        url: https://download3.vmware.com/software/CART23FQ2_LIN64_2206/VMware-Horizon-Client-2206-8.6.0-20094634.x64.bundle
        dest: '.'
    
    - name: Install Horizon Client
      ansible.builtin.shell:
        cmd: 'printf "no\nno\n" | bash VMware-Horizon-Client-2206-8.6.0-20094634.x64.bundle --console --required --eulas-agreed --stop-services'

    - name: Make Directory for SmartCard Support
      ansible.builtin.file:
        state: directory
        path: /usr/lib/vmware/view/pkcs11

    - name: Link pkcs11 For SmartCard Support
      ansible.builtin.file:
        state: link
        src: /usr/lib64/pkcs11/opensc-pkcs11.so
        path: /usr/lib/vmware/view/pkcs11/libpkcs11.so

    - name: Download DoD Certs
      ansible.builtin.get_url:
        url: https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/unclass-certificates_pkcs7_v5-6_dod.zip
        dest: '.'

    - name: Unzip Certs
      ansible.builtin.unarchive:
        src: unclass-certificates_pkcs7_v5-6_dod.zip
        dest: '.'

    - name: Convert Certs to pem
      ansible.builtin.shell:
        cmd: openssl pkcs7 -in Certificates_PKCS7_v5.6_DoD/Certificates_PKCS7_v5.6_DoD.pem.p7b -print_certs -out DoD_CAs.pem

    - name: Copy Certs to etc
      ansible.builtin.copy:
        src: DoD_CAs.pem
        dest: /etc/pki/ca-trust/source/anchors

    - name: Update CA Trust
      ansible.builtin.shell:
        cmd: update-ca-trust

    # - name: Get PIA Installer
    #   ansible.builtin.get_url:
    #     url: https://installers.privateinternetaccess.com/downloads/pia-linux-3.3.1-06924.run
    #     dest: '.'

    # - name: Write install script wrapper
    #   ansible.builtin.copy:
    #     dest: 'test.sh'
    #     content: |
    #       expect -c 'spawn bash /tmp/pia-linux-3.3.1-06924.run; expect "Password:"; send "testpass\n"; interact'

    # - name: Make dummy user, install PIA, remove user
    #   ansible.builtin.shell:
    #     cmd: "{{ item }}"
    #   with_items:
    #     - useradd -UG wheel -p $(openssl passwd -6 testpass) testuser
    #     - expect -c 'spawn ssh -t testuser@localhost "bash /tmp/test.sh"; expect "password:"; send "testpass\n"; interact'
    #     - userdel testuser
    #     - rm -rf /home/testuser

    - name: Write User Profile for Extensions
      ansible.builtin.copy:
        dest: /etc/dconf/db/local.d/00-extensions
        content: |
          [org/gnome/shell]
          # List all extensions that you want to have enabled for all users
          enabled-extensions=['apps-menu@gnome-shell-extensions.gcampax.github.com','caffeine@patapon.info','no-overview@fthx','places-menu@gnome-shell-extensions.gcampax.github.com','window-list@gnome-shell-extensions.gcampax.github.com']

    - name: Write User Favorite Apps
      ansible.builtin.copy:
        dest: /etc/dconf/db/local.d/00-favorite-apps
        content: |
          [org/gnome/shell]
          favorite-apps = ['gnome-terminal.desktop','nautilus.desktop','firefox.desktop','google-chrome.desktop','autopsy.desktop','code.desktop','org.gnome.TextEditor.desktop','putty.desktop','NetworkMiner.desktop','brim.desktop','vmware-view.desktop','piavpn.desktop','com.yubico.yubioath.desktop','org.gnome.tweaks.desktop','org.gnome.Settings.desktop']

    - name: Set User Wallpaper
      ansible.builtin.copy:
        dest: /etc/dconf/db/local.d/00-background
        content: |
          [org/gnome/desktop/background]
          picture-uri='file:///usr/share/backgrounds/wallpapers/low-poly-raven.png'
          picture-uri-dark='file:///usr/share/backgrounds/wallpapers/low-poly-raven.png'
          picture-options='zoom'
          primary-color='000000'
          secondary-color='FFFFFF'
          show-desktop-icons="true"

    - name: Add Window Buttons (maximize, minimize)
      ansible.builtin.copy:
        dest: /etc/dconf/db/local.d/00-windowbuttons
        content: |
          [org/gnome/desktop/wm/preferences]
          button-layout='appmenu:minimize,maximize,close'

    - name: Set Dark Mode
      ansible.builtin.copy:
        dest: /etc/dconf/db/local.d/00-darkmode
        content: |
          [org/gnome/desktop/interface]
          color-scheme='prefer-dark'
          # gtk-theme='Adwaita-dark'

    - name: Get Wallpapers
      ansible.builtin.find:
        patterns: "*.png"
        paths: "/usr/share/backgrounds/wallpapers"
        recurse: yes
      register: wallpapers

    - name: Template Wallpaper XML
      ansible.builtin.copy:
        dest: "/usr/share/gnome-background-properties/{{ item.path.split('/')[-1].split('.')[0] }}.xml"
        content: |
          <?xml version="1.0"?>
          <!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
          <wallpapers>
            <wallpaper deleted='false'>
              <name>{{ item.path.split('/')[-1].split(".")[0].split('-') | title }}</name>
              <filename>/usr/share/backgrounds/wallpapers/{{ item.path.split('/')[-1] }}</filename>
              <filename-dark>/usr/share/backgrounds/wallpapers/{{ item.path.split('/')[-1] }}</filename-dark>
              <options>zoom</options>
              <shade_type>solid</shade_type>
              <pcolor>#000000</pcolor>
              <scolor>#FFFFFF</scolor>
            </wallpaper>
          </wallpapers>
      loop:
        "{{ wallpapers.files }}"

    - name: Update dconf
      ansible.builtin.shell:
        cmd: dconf update

    